from yatapi.scunit import SCUnit

UNKILLABLE_UNITS = [
 SCUnit('\"Alan Turret\"'),
 SCUnit('\"Cantina\"'),
 SCUnit('\"Cave\"'),
 SCUnit('\"Cave-in\"'),
 SCUnit('\"Dark Swarm\"'),
 SCUnit('\"Data Disc\"'),
 SCUnit('\"Disruption Web\"'),
 SCUnit('\"Duke Turret type 1\"'),
 SCUnit('\"Duke Turret type 2\"'),
 SCUnit('\"Flag\"'),
 SCUnit('\"Floor Hatch (UNUSED)\"'),
 SCUnit('\"Goliath Turret\"'),
 SCUnit('\"Independent Command Center\"'),
 SCUnit('\"Independent Starport\"'),
 SCUnit('\"Khalis Crystal\"'),
 SCUnit('\"Khaydarin Crystal\"'),
 SCUnit('\"Khaydarin Crystal Formation\"'),
 SCUnit('\"Left Pit Door\"'),
 SCUnit('\"Left Upper Level Door\"'),
 SCUnit('\"Map Revealer\"'),
 SCUnit('\"Mineral Field (Type 1)\"'),
 SCUnit('\"Mineral Field (Type 2)\"'),
 SCUnit('\"Mineral Field (Type 3)\"'),
 SCUnit('\"Mining Platform\"'),
 SCUnit('\"Nuclear Missile\"'),
 SCUnit('\"Protoss Beacon\"'),
 SCUnit('\"Protoss Flag Beacon\"'),
 SCUnit('\"Protoss Marker\"'),
 SCUnit('\"Protoss Unused type 1\"'),
 SCUnit('\"Protoss Unused type 2\"'),
 SCUnit('\"Psi Emitter\"'),
 SCUnit('\"Right Pit Door\"'),
 SCUnit('\"Right Upper Level Door\"'),
 SCUnit('\"Ruins\"'),
 SCUnit('\"Scanner Sweep\"'),
 SCUnit('\"Start Location\"'),
 SCUnit('\"Tank Turret type 1\"'),
 SCUnit('\"Tank Turret type 2\"'),
 SCUnit('\"Terran Beacon\"'),
 SCUnit('\"Terran Flag Beacon\"'),
 SCUnit('\"Terran Marker\"'),
 SCUnit('\"Unused Terran Bldg type 1\"'),
 SCUnit('\"Unused Terran Bldg type 2\"'),
 SCUnit('\"Unused Zerg Bldg\"'),
 SCUnit('\"Unused Zerg Bldg 5\"'),
 SCUnit('\"Unused type 1\"'),
 SCUnit('\"Unused type 2\"'),
 SCUnit('\"Unused unit 228\"'),
 SCUnit('\"Uraj Crystal\"'),
 SCUnit('\"Vespene Geyser\"'),
 SCUnit('\"Zerg Beacon\"'),
 SCUnit('\"Zerg Flag Beacon\"'),
 SCUnit('\"Zerg Marker\"')
]